vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       propertys:
           uri_prefix: /images/propertys
           upload_destination: '%kernel.project_dir%/public/images/propertys'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
