controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

    
contact:
    path: /contact
    controller: App\Controller\ContactController::index
